name: server
description: Dart Functions Framework
version: 1.0.0
homepage: https://github.com/subfuzion/dart-scratch
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.7.0
  shelf: ^0.7.5

dev_dependencies:
  pedantic: ^1.9.0
